### ISSUE TITLE
New version causing "User identification required"

### ISSUE THREAD

**Issue by 45kb** [720kb/comunicator#3]
Just included:

```
<script src="https://cdn.rawgit.com/720kb/comunicator/master/src/js/comunicator.js"></script>
<script src="https://cdn.rawgit.com/720kb/comunicator/master/src/js/raf.js"></script>
<script src="https://cdn.rawgit.com/720kb/comunicator/master/dist/comunicator-angular.min.js"> </script>
```

Websocket state is opened and "Kick OFF DOM event is printed in console"
Then when trying to broadcast or sendTo i get in console: 

```
Uncaught (in promise) User identification required
```

There is also this error in console: 

```
"Uncaught (in promise) TypeError: Cannot read property 'websocket' of undefined" comunicator.js line 145
```

NB: I did not changed any angular or node code that i was using with https://cdn.rawgit.com/720kb/comunicator/74c530249206e904e4092d35aa460e9dfc04fc15/dist/comunicator-angular.min.js (which worked well)

**Comment by wouldgo** [comment]
modify the `comunicator.js` with `https://rawgit.com/720kb/comunicator/4220b6903f7f4aca8b1c991d06f373a28f56212b/src/js/comunicator.js`.

**Comment by 45kb** [comment]
First error is fixed, second one still, all i am doing in the code is open the websocket and make userIsPresent()  but after Kick Off DOM event in console i see this error still:

   Uncaught (in promise) TypeError: Cannot read property 'websocket' of undefined {stack: (...), message: "Cannot read property 'websocket' of undefined"}

comunicator.js:145

**Comment by 45kb** [comment]
Now after userIsPresent i send a broadcast() message but it returns in console 
    Uncaught (in promise) User identification required

**Comment by wouldgo** [comment]
put [here](https://github.com/720kb/comunicator/blob/master/src/js/comunicator.js#L256) resolveComunicator.bind(this) instead of resolveComunicator

**Comment by wouldgo** [comment]
also put .bind(this) also on the resolve params.

**Comment by 45kb** [comment]
All done, https://github.com/720kb/comunicator/commit/c930d9c61ab56ed5ef01b8913ee955d6ec0880c8

i would say FIXED need to check broadcast now
