### ISSUE TITLE
BE Sockets Array - queue message is sent before user is in connected sockets array

### ISSUE THREAD

**Issue by 45kb** [720kb/comunicator#6]
There is a little problem when:
- user1 and user2 are connected
- BE goes down
- user1 sends a queue message to user2
- BE returns up and running
- user1 and user2 are re-connected to ws
- user1 queue message returns: "No user2 is connected to the sockets"

Looks like node sockets array is empty (or missing the specific user) before the queue message is sent.

:hammer:

**Comment by wouldgo** [comment]
Closed with df20d2d770b913040a8fbdb7895815c3009e3904

Now the node comunicator part stores all the send that aren't delivered and then waits for the `join` opcode to flush the queued messages.

**Comment by 45kb** [comment]
:dancers:  :dancers: :dancers:  :dancers:
